<a href="https://colab.research.google.com/github/kubusccnp/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello Colab')

Hello Colab


In [4]:
import numpy as np

In [5]:
np.__version__

'1.21.6'

In [6]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__'

In [ ]:
help(np.array)

In [8]:
x = np.array([1, 3])

In [9]:
print(x)

[1 3]


In [12]:
type(x)

numpy.ndarray

In [13]:
x.ndim

1

In [14]:
x.shape

(2,)

In [15]:
x.size

2

In [16]:
x.dtype

dtype('int64')

In [19]:
x= np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [20]:
x.dtype

dtype('float64')

In [22]:
x = np.array([[1,2], [-3,1]])

In [23]:
x.ndim

2

In [24]:
x.shape

(2, 2)

In [26]:
x = np.array([[1,2,4], [4,2,1]])

In [27]:
x.shape

(2, 3)

In [32]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [34]:
A = np.array([1,2,3], dtype='complex')
print(A.dtype)
print(A)

complex128
[1.+0.j 2.+0.j 3.+0.j]


In [35]:
A = np.array([1.1,2.7,3.5], dtype='int')
A

array([1, 2, 3])

In [36]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [38]:
A = np.array([24, 128, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

In [40]:
a = np.zeros([4, 10])
a.dtype

dtype('float64')

In [41]:
a = np.zeros([4, 10], dtype='int')
a.dtype

dtype('int64')

In [43]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
np.full([3,3], fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [45]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [47]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [50]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [52]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [54]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [56]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A, B)

[3 1 4 2] [ 3 -1  3  2]


In [57]:
A+B

array([6, 0, 7, 4])

In [58]:
A-B

array([0, 2, 1, 0])

In [59]:
A*B

array([ 9, -1, 12,  4])

In [60]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [61]:
A+3

array([6, 4, 7, 5])

In [62]:
2*A

array([6, 2, 8, 4])

In [63]:
A + 3*B

array([12, -2, 13,  8])

In [64]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [65]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [66]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [67]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [68]:
X*Y

array([[6, 0],
       [2, 0]])

In [69]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [70]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [71]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [72]:
np.random.seed(0)

In [74]:
np.random.randn()

0.4001572083672233

In [75]:
np.random.randn(10)

array([ 0.97873798,  2.2408932 ,  1.86755799, -0.97727788,  0.95008842,
       -0.15135721, -0.10321885,  0.4105985 ,  0.14404357,  1.45427351])

In [76]:
np.random.randn(10,4)

array([[ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 ],
       [-0.50965218, -0.4380743 , -1.25279536,  0.77749036],
       [-1.61389785, -0.21274028, -0.89546656,  0.3869025 ]])

In [77]:
np.random.rand()

0.1965823616800535

In [78]:
np.random.rand(10,2)

array([[0.36872517, 0.82099323],
       [0.09710128, 0.83794491],
       [0.09609841, 0.97645947],
       [0.4686512 , 0.97676109],
       [0.60484552, 0.73926358],
       [0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145]])

In [79]:
np.random.randint(10)

1

In [80]:
np.random.randint(low=10, high=101)

60

In [81]:
np.random.randint(low=10, high=101, size=10)

array([37, 24, 51, 68, 75, 46, 20, 96, 53, 21])

In [82]:
np.random.choice([4,2,1,5,6])

1

In [83]:
np.random.choice(['py', 'js', 'sq'])

'py'

In [84]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
np.random.shuffle(data)

In [86]:
data

array([1, 4, 7, 5, 2, 3, 8, 9, 6, 0])

In [87]:
np.exp(1)

2.718281828459045

In [88]:
np.sqrt(4)

2.0

In [89]:
np.all([2,3,1])

True

In [90]:
np.any([1,2,3])

True

In [91]:
np.any([0,0,0])

False

In [92]:
np.all([2,3,4])

True

In [95]:
A = np.random.rand(5)
A

array([0.22308163, 0.95274901, 0.44712538, 0.84640867, 0.69947928])

In [96]:
np.argmax(A)

1

In [97]:
A[np.argmax(A)]

0.952749011516985

In [98]:
np.argmin(A)

0

In [99]:
np.argsort(A)

array([0, 2, 4, 3, 1])

In [100]:
np.argmax(A)

1

In [101]:
np.max(A)

0.952749011516985

In [102]:
np.min(A)

0.2230816326406183

In [103]:
np.mean(A)
np.median(A)

0.6994792753175043

In [104]:
np.std(A)

0.26637630279339825

In [106]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [107]:
A[2]

2

In [109]:
A[:2]

array([0, 1])

In [110]:
A[[0,2]]

array([0, 2])

In [111]:
A[10:15]

array([10, 11, 12, 13, 14])

In [114]:
A = A.reshape(4,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [115]:
A[0]

array([0, 1, 2, 3, 4])

In [116]:
A[1]

array([5, 6, 7, 8, 9])

In [117]:
A[:,1]

array([ 1,  6, 11, 16])

In [118]:
A[:,0]

array([ 0,  5, 10, 15])

In [119]:
A[1,1]

6

In [123]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [124]:
A[1,2]=14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [128]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [130]:
A = np.reshape(A, [4,5])
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [131]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [132]:
for row in A:
  print(row[0])

0
5
10
15


In [133]:
for row in A:
  print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


In [134]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [135]:
A.shape

(4, 5)

In [136]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [137]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [138]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [139]:
A = np.arange(start=-10, stop=10, step=0.5)
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [141]:
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [142]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [143]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [145]:
np.bitwise_and(A>-5, A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [146]:
A[np.bitwise_and(A>-5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])