<a href="https://colab.research.google.com/github/kubusccnp/data-science-bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
# utworzenie wektora
v1 = np.array([0,4])
v1

array([0, 4])

In [3]:
np.linalg.norm(v1)

4.0

In [4]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [5]:
np.linalg.norm(v1)

4.123105625617661

In [6]:
v2 = np.array([-10,10,13])
v2

array([-10,  10,  13])

In [7]:
np.linalg.norm(v2)

19.209372712298546

In [8]:
p=np.array([3,0])
q=np.array([0,4])

In [9]:
np.linalg.norm(p-q)

5.0

In [10]:
p=np.array([3,0,1])
q=np.array([0,4,2])

In [11]:
np.linalg.norm(p-q)

5.0990195135927845

In [15]:
X = np.array([[5,3], [3,9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [17]:
Z = np.dot(X,Y)
Z

array([[ 2],
       [-6]])

In [18]:
Z.shape

(2, 1)

In [19]:
A = np.array([[2,4], [-1,3]])
np.linalg.det(A)

9.999999999999998

In [20]:
A = np.array([[2,4], [-1,3]])
np.trace(A)

5

In [21]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [22]:
A

array([[ 2,  4],
       [-1,  3]])

In [24]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [25]:
np.dot(A,B)

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [26]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [27]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [28]:
A = np.array([ [2,4], [1,-1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [29]:
B = np.array([[10], [-1]])
B

array([[10],
       [-1]])

In [30]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv,B)
X

array([[1.],
       [2.]])

In [31]:
X.shape

(2, 1)